version: '3.1'
services:

  # opa using running local bundle in secured mode:
  opa:
    image: openpolicyagent/opa:0.69.0
    ports:
      - "8181:8181"
    volumes:
      - ./config-demo.yaml:/etc/opa/config.yaml
      - ./bundle:/bundle
    command:
      - run
      - --disable-telemetry
      - --server
      - --log-level
      - error
      - --log-format
      - json-pretty
      - --authorization
      - basic
      - --addr
      - :8181
      - --set
      - default_decision=policies
      - --config-file
      - /etc/opa/config.yaml
      - --bundle
      - /bundle
    # opa run --disable-telemetry --server --log-level error --log-format=json-pretty --authorization=basic --addr :8181 --set default_decision=policies --config-file ./config.yaml
