apiVersion: v1
kind: ConfigMap
metadata:
  name: daggerengine-engine-config
data:
  engine.toml: |
    debug = false
    insecure-entitlements = ["security.insecure"]
    [worker.oci]
    gc = true
    gckeepstorage = "7GB"
    [[worker.oci.gcpolicy]]
    keepBytes = "7GB"
    keepDuration = "300h"
    filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
    [[worker.oci.gcpolicy]]
    keepBytes = "7GB"
    keepDuration = "300h"
    [[worker.oci.gcpolicy]]
    keepBytes = "7GB"
    [[worker.oci.gcpolicy]]
    all = true
    keepBytes = "7GB"
