apiVersion: v1
kind: Service
metadata:
  name: daggerengine
spec:
  ports:
    - name: engine
      port: 1234
      protocol: TCP
      targetPort: 1234
  selector:
    app: daggerengine
  type: ClusterIP
